apiVersion: v1
kind: Pod
spec:
  containers:
    # ruleid: run-as-non-root
    - name: nginx
      image: nginx
    # ruleid: run-as-non-root
    - name: postgres
      image: postgres
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
    # ok: run-as-non-root
    - name: haproxy
      image: haproxy
      securityContext:
        runAsNonRoot: true
