name: num-rules

on:
  push:
    branches:
    - release
  schedule:
  - cron: 0 0 * * *

jobs:
  run_benchmarks:
    if: github.repository == 'returntocorp/semgrep-rules'
    runs-on: ubuntu-latest
    name: Update Dashboard
    steps:
    - uses: actions/checkout@v2
    - name: record stats
      run: |
        NUM=$(grep -R -e'- id:' * | wc -l | bc) && curl --fail -L -X POST https://dashboard.semgrep.dev/api/metric/semgrep-rules.num -d $NUM
    - name: record registry/all stats
      run: |
        NUM=$(curl --fail -L https://semgrep.dev/c/r/all | grep -e'- id:' - | wc -l | bc) && curl --fail -L -X POST https://dashboard.semgrep.dev/api/metric/registry.rules.num -d $NUM
