name: rule-benchmarks

on:
  schedule:
  - cron: '*/15 * * * *'

jobs:
  run_benchmarks:
    runs-on: ubuntu-latest
    name: Run benchmarks for each rule
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7.7'
    - name: Install pipenv
      shell: bash
      run: |
        pip3 install pipenv
    - name: Install pipenv dev dependencies
      shell: bash
      run: |
        pipenv install -d
    - name: Get formatted date
      id: vars
      shell: bash
      run: |
        echo "::set-output name=today::$(date +'%Y-%m-%d')"
    - name: Run benchmarks
      shell: bash
      run: |
        pipenv run pytest --timeout 60 --benchmark-only --benchmark-min-rounds=2 --benchmark-save=${{ steps.vars.output.today }}.txt --benchmark-json=${{ steps.vars.outputs.today }}.json tests/performance/ | tee test-logs.txt
    - name: Upload text results
      uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: ${{ steps.vars.outputs.today }}.txt
        path: ${{ steps.vars.outputs.today }}.txt
    - name: Upload text log
      uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: test-logs.txt
        path: test-logs.txt
    - name: Upload JSON results
      uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: ${{ steps.vars.outputs.today }}.json
        path: ${{ steps.vars.outputs.today }}.json