name: semgrep-rules-test-develop

on:
  pull_request:
    branches:
    - develop
  push:
    branches:
    - develop

jobs:
  test-latest:
    name: rules-test-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: validate rules
      run: |
        docker run --rm -v $(PWD):/src returntocorp/semgrep:develop --validate --config /src
    - name: test with semgrep develop branch
      run: |
        docker run --rm -v $(PWD):/src returntocorp/semgrep:develop --test --test-ignore-todo
