name: semgrep-rules-test-develop
on:
  pull_request:
    branches:
    - develop
  push:
    branches:
    - develop
jobs:
  # Note: if you change this test there will likely need to be a
  # corresponding change in returntocorp/semgrep
  test-develop:
    name: rules-test-develop
    runs-on: ubuntu-20.0
    steps:
    - uses: actions/checkout@v2
      with:
        path: semgrep-rules
    - name: delete stats directory
      run: rm -rf semgrep-rules/stats
    - name: delete fingerprints directory
      run: rm -rf semgrep-rules/fingerprints
    - name: validate rules
      run: |
        export SEMGREP="docker run --rm -w /src -v ${GITHUB_WORKSPACE}/semgrep-rules:/src returntocorp/semgrep:develop semgrep"
        make -C "$GITHUB_WORKSPACE"/semgrep-rules validate
    - name: test with semgrep develop branch
      run: |
        export SEMGREP="docker run --rm -w /src -v ${GITHUB_WORKSPACE}/semgrep-rules:/src returntocorp/semgrep:develop semgrep"
        make -C "$GITHUB_WORKSPACE"/semgrep-rules test-only
