name: update-semgrep-live

on:
  push:
    branches:
    - develop

jobs:
  build:
    name: Update semgrep.live
    runs-on: ubuntu-latest
    steps:
    - name: update semgrep.live
      run: curl --fail -X POST -L https://semgrep.dev/api/admin/update-registry
